homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1/', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story5mk2/', include('story5mk2.urls')),


]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'


urlpatterns = [
    path('', views.story1, name='story1'),
    
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.bio, name='bio'),
    path('skill/', views.skill, name='skill'),
    path('views/', views.portofolio, name='portofolio'),
    path('history/', views.history, name='history'),
    path('contact/', views.contact, name='contact'),
    
]

story5mk2/urls.py
from django.urls import path
from . import views

app_name = 'story5mk2'

urlpatterns = [
    path('', views.siakenji, name='siakenji'),
    path('addMatkul/', views.addMatkul, name='addMatkul'),
    path("matkul/<int:id>",views.detailMatkul,name="detailMatkul"),
    path("deleteMatkul/<int:id>",views.deleteMatkul,name="deleteMatkul")
]

homepage/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5mk2/models.py
from django.db import models
from django.shortcuts import reverse


semester_choices = [
    ("Gasal 2019/2020","Gasal 2019/2020"),
    ("Genap 2019/2020","Genap 2019/2020"),
    ("Gasal 2020/2021","Gasal 2020/2021"),
    ("Genap 2020/2021","Genap 2020/2021"),
    ("Gasal 2021/2022","Gasal 2021/2022"),
    ("Genap 2021/2022","Genap 2021/2022")
]

class MataKuliah(models.Model):
    nama = models.TextField(max_length = 50)
    dosen = models.TextField(max_length = 50)
    jumlahSks = models.IntegerField()
    deskripsi = models.TextField(max_length = 500)
    semester = models.TextField(choices = semester_choices)
    ruangan = models.TextField(max_length = 50)

    def __str__(self):
        return "{} ({})".format(self.nama,self.dosen)

    def get_absolute_url(self):
        return reverse("story5mk2:detailMatkul",args=[self.id])

story5mk2/forms.py
from django import forms
from .models import MataKuliah

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__"

homepage/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

story1/views.py
from django.shortcuts import render

def story1(request):
    return render(request, 'story1.html')

story3/views.py
from django.shortcuts import render

# Create your views here.
def bio(request):
    return render(request, 'bio_view.html')

def contact(request):
    return render(request, 'contact_view.html')

def history(request):
    return render(request, 'history_view.html')

def skill(request):
    return render(request, 'skill_view.html')

def portofolio(request):
    return render(request, 'portofolio_view.html')

story5mk2/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import MatkulForm
from .models import MataKuliah

# Create your views here.
def siakenji(request):
    context = {
        "listMataKuliah" : MataKuliah.objects.all().order_by("-id"),
    }
    return render(request, 'siakenji_view.html', context)

def addMatkul(request):
    if request.method == 'POST':
        matkulForm = MatkulForm(request.POST)
        if matkulForm.is_valid():
            matkulForm.save()
        return redirect("story5mk2:siakenji")
    else:
        return render(request,"addMatkul_view.html")

def detailMatkul(request,id):
    matkul = MataKuliah.objects.get(id=id)
    context = {
        "mataKuliah" : matkul
    }
    return render(request,"detailMatkul_view.html",context)

def deleteMatkul(request,id):
    if request.method == "POST":
        mataKuliah = MataKuliah.objects.get(id=id)
        mataKuliah.delete()
    return redirect("story5mk2:siakenji")

homepage/templates/homepage.html
<html>
    <head>
        <title>Homepage</title>
    </head>
    <body>
        <a href="{% url 'story1:story1' %}">to Story 1</a>
        <a href="{% url 'story3:bio' %}">to Story 3</a>
        <a href="{% url 'story5mk2:siakenji' %}">to Story 5</a>
    </body>
</html>

story1/templates/story1.html
<!DOCTYPE html>
{% load static %}
<html>
    <title>Story 1</title>
    <link rel="icon" type="image/png" href="{% static 'photos/bg2.png' %}"/>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}"> 
    </head>
    <body>
        <div class="contents">
            <div class="middle-column">
                <h1 style="align-self: center;" >Biodata</h1>
                <div style="align-self: center;">
                    <img src={% static 'photos/ID18.jpg' %} alt="Me" width="200" height="250">
                </div>
                
                <div class="middle-row">
                    <div class="desc" style="width: 50%; line-height: 25px;">
                        <table>
                            <tr>
                                <td>Nama</td>
                                <td>: Hendrico Kristiawan</td>
                            </tr>
                            <tr>
                                <td>NPM</td>
                                <td>: 1906350912</td>
                            </tr>
                            <tr>
                                <td>Angkatan</td>
                                <td>: 2019</td>
                            </tr>
                            <tr>
                                <td>Tempat Kuliah</td>
                                <td>: Universitas Indonesia</td>
                            </tr>
                            <tr>
                                <td>Hobi</td>
                                <td>: Menonton film</td>
                            </tr>
                            <tr>
                                <td>Deskripsi</td>
                                <td>: Saya seorang mahasiswa fasilkom UI</td>
                            </tr>
                        </table>
                    </div> 
                </div>
                <h1 style="align-self: center;" >Riwayat Pendidikan</h1>
                <div class="desc" style="width: 50%; line-height: 25px;">
                    <table>
                        <tr>
                            <th>Sekolah</th>
                            <th>Tahun</th>
                        </tr>
                        <tr>
                            <td>SDN Mekarsari 1</td>
                            <td>: 2007 - 2013</td>
                        </tr>
                        <tr>
                            <td>SMPN 1 Tambun Selatan</td>
                            <td>: 2013 - 2016</td>
                        </tr>
                        <tr>
                            <td>SMAN 1 Tambun Selatan</td>
                            <td>: 2016 - 2019</td>
                        </tr>
                        <tr>
                            <td>Universitas Indonesia</td>
                            <td>: 2019 - sekarang</td>
                        </tr>
                    </table>
                </div>
                <h1 style="align-self: center;" >Kontak Saya</h1>
                <div class="middle-row">
                    <div class="middle-column" style="width: auto; font-size: 20px;">
                        <img src="{% static 'photos/icons8-gmail-96.png' %}" width="96" height="96" alt="gmail" style="align-self: center;">
                        hendrico.kristiawan@ui.ac.id
                    </div>
                    <a target= "_blank" href="https://github.com/IoriU"><img src="{% static 'photos/icons8-github-96.png' %}" alt="github"></a>
                    <a target= "_blank" href="https://www.linkedin.com/in/hendrico-kristiawan-36771317a/"><img src="{% static 'photos/icons8-linkedin-96.png' %}" alt="linkedin"></a>
                </div>

            </div>
            
            
        </div>

    </body>

</html>

story3/templates/base3.html
<!DOCTYPE html>
{% load static %}
<html>
    {% block title %}
    {% endblock title %}
    <link rel="icon" type="image/png" href="{% static 'photos/bg2.png' %}"/>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/styles3.css' %}">
        <script>
            function clicked(id, class_name){
                if (document.getElementById(id + "-unclicked")){
                    document.getElementById(id + "-container").className= (class_name + "-clicked");
                    document.getElementById(id + "-unclicked").id= (id + "-clicked");
                } else if (document.getElementById(id + "-clicked")){
                    document.getElementById(id + "-container").className= (class_name);
                    document.getElementById(id + "-clicked").id= (id + "-unclicked");
                }
                
            }
            function navbarView() {
                
                var x = document.getElementById("navbar");
                if (x.className === "navbar") {
                    x.className += "-responsive";
                    document.getElementById("expand").innerHTML = "Back"
                } else {
                    x.className = "navbar";
                    document.getElementById("expand").innerHTML = "Change Page"
                }
            }
           
    
        </script>  
    </head>
    <body>
        <div class="nav-bg">
            <div class="navbar" id="navbar">
                <a href="{% url 'story3:bio' %}">Bio</a>
                <a href="{% url 'story3:skill' %}">Skill</a>
                <a href="{% url 'story3:portofolio' %}">Portofolio</a>
                <a href="{% url 'story3:history' %}">History</a>
                <a href="{% url 'story3:contact' %}">Contact</a>
                <a href="{% url 'story1:story1' %}">Story 1</a>
                <a href="javascript:void(0);" class="expand" id="expand" onclick="navbarView()">
                    Change Page
                </a>
            </div>
        </div>
        <div class="header-container">
            <header>
            {% block header %}
            {% endblock header %}
            </header>
        </div>
        
        <div>
            {% block content %}
            {% endblock content %}
        </div>

    </body>

</html>

story3/templates/bio_view.html
{% extends 'base3.html' %}
{% load static %}

{% block title %}
    <title>Bio</title>
{% endblock title %}

{% block header %}
    <h1>Bio</h1>
{% endblock header %}

{% block content %}
    <div class="contents">
        <div class="left-column">
            
            <div class="textbox" id="name" onclick="clicked(this.id, 'content-container')">
                <div id="name-unclicked"></div>
                <div class="content-container" id="name-container">
                    
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image">
                    <div class="content-text">Hendrico Kristiawan</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image">
                    <div class="cover-text">Name</div>
                </div>
                
            </div>
            
            <div class="order-image">
                <img src={% static 'photos/ID18.jpg' %} alt="Me" class= "image-relative" width="200" height="250">
            </div>
            <div class="textbox" id="npm" onclick="clicked(this.id, 'content-container')">
                <div id="npm-unclicked"></div>
                <div class="content-container" id="npm-container">
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image">
                    <div class="content-text">1906350912</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image">
                    <div class="cover-text">NPM</div>
                </div>
            </div>
        </div>
        <div class="right-column">

            <div class="textbox-rotate" id="university", onclick="clicked(this.id, 'content-container-rotate')">
                <div class="content-container-rotate" id="university-container">
                    <div id="university-unclicked"></div>
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                    <div class="content-text-rotate">University of Indonesia</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                    <div class="cover-text-rotate">University</div>
                </div>
                
            </div>
            <div class="textbox-rotate" id="generation", onclick="clicked(this.id, 'content-container-rotate')">
                <div class="content-container-rotate" id="generation-container">
                    <div id="generation-unclicked"></div>
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                    <div class="content-text-rotate">2019</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                    <div class="cover-text-rotate">Generation</div>
                </div>
                
            </div>
            <div class="textbox-rotate" id="place", onclick="clicked(this.id, 'content-container-rotate')">
                <div class="content-container-rotate" id="place-container">
                    <div id="place-unclicked"></div>
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                    <div class="content-text-rotate">Bekasi</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                    <div class="cover-text-rotate">Place</div>
                </div>
                
            </div>
            <div class="textbox-rotate" id="hobby", onclick="clicked(this.id, 'content-container-rotate')">
                <div class="content-container-rotate" id="hobby-container">
                    <div id="hobby-unclicked"></div>
                    <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                    <div class="content-text-rotate">Watching movies</div>
                </div>
                <div class="cover-container">
                    <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                    <div class="cover-text-rotate">Hobby</div>
                </div>
                
            </div>
        </div>
        <div class="android-ver">
            <div class="odd-row">
                Name : Hendrico Kristiawan
            </div>
            <div class="even-row">
                NPM : 1906350912
            </div>
            <div class="odd-row">
                University : Universitas Indonesia
            </div>
            <div class="even-row">
                Generation : 2019
            </div>
            <div class="odd-row">
                Place : Bekasi
            </div>
            <div class="even-row">
                Hobby : Watching movies
            </div>
        </div>
    </div>
    <div class="desc">
        <p>I am a computer science student at University of Indonesia.<br>
        I am interested in making games and learning AI.</p>
    </div>
{% endblock %}

story3/templates/contact_view.html
{% extends 'base3.html' %}
{% load static %}

{% block title %}
<title>Contact</title>
{% endblock title %}

{% block header %}
<h1>Contact</h1>
{% endblock header %}

{% block content %}
    <div class="contents">
                
        <div class="left-column">
            <div class="start-row">
                <img src="{% static 'photos/icons8-gmail-96.png' %}" alt="gmail" class="icon" style="float: left;">
                <div class="flag-shape">
                    <div>hendrico.kristiawan@ui.ac.id</div>
                </div>
            </div>

            <div class="start-row">
                <img src="{% static 'photos/icons8-github-96.png' %}" alt="github" class="icon" style="float: left;">
                <div class="flag-shape">
                    <a target= "_blank" href="https://github.com/IoriU">To my profile</a>
                </div>
            </div>

            <div class="start-row">
                <img src="{% static 'photos/icons8-linkedin-96.png' %}" alt="linkedin" class="icon" style="float: left;">
                <div class="flag-shape">
                    <a target= "_blank" href="https://www.linkedin.com/in/hendrico-kristiawan-36771317a/">To my profile</a>
                </div>
            </div>
        </div>
        <div class="right-column" style="margin-top: 0;">
            <div class="desc">
                <p>Want to know more <br>about me ?<br><br><br><br><br>Feel free to contact me!</p>
            </div>
        </div>
    </div>
{% endblock %}

story3/templates/history_view.html
{% extends 'base3.html' %}
{% load static %}

{% block title %}
<title>History</title>
{% endblock title %}

{% block header %}
<h1>History</h1>
{% endblock header %}

{% block content %}
    <div class="contents">
        <div class="middle-column">
            <img src="{% static 'photos/sd.jpg' %}" id="image" alt="placeholder" class="history-image">
            <div class="middle-row" style="margin-top: 20px;">
                <div class="left-triangle" id="left" onclick="clicked(this.id)"></div>
                <div class="middle-column">
                    <div class="trapezoid-up-big">
                        <div style="position: relative; bottom: 37px" id="edu">SDN Mekarsari 1</div>
                    </div>
                    <div class="trapezoid-down-big">
                        <div style="position: relative; top: 15px" id="year">2007 - 2013</div>
                    </div>
                </div>
                <div class="right-triangle" id="right" onclick="clicked(this.id)"></div>
            </div>
    </div>
{% endblock %}


        
        
            
            

</html>

story3/templates/portofolio_view.html
{% extends 'base3.html' %}
{% load static %}

{% block title %}
<title>Portofolio</title>
{% endblock title %}

{% block header %}
<h1>Portofolio</h1>
{% endblock header %}

{% block content %}
    <div class="contents" style="justify-content: flex-start;">
                
        <div class="left-column">
            <img src="https://via.placeholder.com/150x150" alt="placeholder" width="300px" height="200px">
            <div style="margin-left: 22pt;">
                <div class="parallelogram">
                    <div>
                        Unity Project
                    </div>
                </div>
                <div class="parallelogram-rotate">
                    <div>
                        <a target= "_blank" href="https://github.com/IoriU/Gravity">Gravity</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

story3/templates/skill_view.html
{% extends 'base3.html' %}
{% load static %}

{% block title %}
<title>Skill</title>
{% endblock title %}

{% block header %}
<h1>Skill</h1>
{% endblock header %}

{% block content %}
    <div class="contents">
                
        <div class="left-column">
            <div style="display: flex;">
                <img src={% static 'photos/icons8-html-5-96.png' %} alt="Icon" style="float: left;">
                <div class="normal-text">6 months experiences</div>
                <div class="textbox" id="html" onclick="clicked(this.id, 'content-container')">
                    <div id="html-unclicked"></div>
                    <div class="content-container" id="html-container">
                        
                        <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image">
                        <div class="content-text">6 months experiences</div>
                    </div>
                    <div class="cover-container">
                        <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image">
                        <div class="cover-text">HTML</div>
                    </div>
                    
                </div>
            </div>
            <div style="margin-top: 40px; display: flex;">
                <img src={% static 'photos/icons8-python-96.png' %} alt="Icon" style="float: left;">
                <div class="normal-text">1 year experience</div>
                <div class="textbox" id="python" onclick="clicked(this.id, 'content-container')">
                    <div id="python-unclicked"></div>
                    <div class="content-container" id="python-container">
                        <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image">
                        <div class="content-text">1 year experience</div>
                    </div>
                    <div class="cover-container">
                        <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image">
                        <div class="cover-text">Python</div>
                    </div>
                </div>
            </div>

            

        
            
        </div>
        <div class="right-column">
            <div style="display: flex;"> 
                <img src={% static 'photos/icons8-unity-100.png' %} alt="Icon" class="android-img">
                <div class="normal-text">6 months experience</div>
                <div class="textbox-rotate" id="unity", onclick="clicked(this.id, 'content-container-rotate')">
                    <div class="content-container-rotate" id="unity-container">
                        <div id="unity-unclicked"></div>
                        <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                        <div class="content-text-rotate">6 months experiences</div>
                    </div>
                    <div class="cover-container">
                        <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                        <div class="cover-text-rotate">Unity</div>
                    </div>
                    
                </div>
            </div>
            
            <div style="margin-top: 40px; display: flex">
                <img src={% static 'photos/java.png' %} alt="Icon" class="android-img" width="96" height="96">
                <div class="normal-text">6 months experience</div>
                <div class="textbox-rotate" id="java", onclick="clicked(this.id, 'content-container-rotate')">
                    <div class="content-container-rotate" id="java-container">
                        <div id="java-unclicked"></div>
                        <img src={% static 'photos/smalltext.png' %} alt="Content" class= "image-rotate" width="350" height="50">
                        <div class="content-text-rotate">6 months experiences</div>
                    </div>
                    <div class="cover-container">
                        <img src={% static 'photos/smallbox.png' %} alt="Cover" class= "image-rotate" width="350" height="50">
                        <div class="cover-text-rotate">Java</div>
                    </div>
                    
                </div>
            </div>
        
        </div>

            
        </div>
        
    </div>    
{% endblock %}

story5mk2/templates/addMatkul_view.html
{% extends 'base5.html' %}
{% load static %}

{% block main %}
    <div class="column-center">
        <div class="row-center">
            <h1>Tambah Matkul</h1>
        </div>

        <div class="add-block">
            <div class="column-center">
                <form method="POST" action="{% url 'story5mk2:addMatkul' %}">
                    {% csrf_token %}
                    <div class="ask">
                        Name
                        <br>
                        <input placeholder="Nama mata kuliah" name="nama" required>
                    </div>
                    <div class="ask">
                        Kode Ruangan
                        <br>
                        <input placeholder="Kode Ruangan" name="ruangan" required>
                    </div>
                    <div class="ask">
                        Pengajar
                        <br>
                        <input placeholder="Nama dosen" name="dosen" required>
                    </div>
                    <div class="ask">
                        Semester
                        <br>
                        <select name="semester" required>
                            <option value="Gasal 2019/2020">Gasal 2019/2020</option>
                            <option value="Genap 2019/2020">Genap 2019/2020</option>
                            <option value="Gasal 2020/2021">Gasal 2020/2021</option>
                            <option value="Genap 2020/2021">Genap 2020/2021</option>
                            <option value="Gasal 2021/2022">Gasal 2021/2022</option>
                            <option value="Genap 2021/2022">Genap 2021/2022</option>
                            </select>
                    </div>
                    <div class="ask">
                        Jumlah SKS
                        <br>
                        <input type="number" value=1 name="jumlahSks" required>
                    </div>
                    <div class="ask">
                        Deskripsi
                        <br>
                        <textarea placeholder="Deskripsi" name="deskripsi" rows="4" required></textarea>
                    </div>
                    <button type="submit">Add Matkul</button>
                </form>
            </div>
        </div>
        

    </div>
{% endblock main %}

story5mk2/templates/base5.html
{% load static %}

<html>
    <head>
        <title>Siak En Ji</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/styles5.css' %}">
    </head>
    <body>
        <div class="navbar">
            <ul>
                <li style="float: left;"><a href="{% url 'story5mk2:siakenji' %}">Siak En Ji</a></li>
                <li><a href="{% url 'story5mk2:addMatkul' %}">Daftar Matkul</a></li>
            </ul>
        </div>
        <div class="contents">
            {% block main %}
            {% endblock main %}
        </div>
        
    </body>
</html>

story5mk2/templates/detailMatkul_view.html
{% extends 'base5.html' %}
{% load static %}
{% block main %}
  <div class="row-center">
    <h1>Info Kelas</h1>
  </div>
  <div class="column-center">
    <div class="detail-block">
      <div class="answer">
        <p>Nama Mata Kuliah</p>
          {{mataKuliah.nama}}
      </div>
      <div class="row-center">
        <div class="column-center-2">
          <div class="answer">
            <p>Ruangan</p>
            {{mataKuliah.ruangan}}
          </div>
          <div class="answer">
            <p>Pengajar</p>
              {{mataKuliah.dosen}}
          </div>
        </div>
        <div class="column-center-2">
          <div class="answer">
            <p>Semester</p>
              {{mataKuliah.semester}}
          </div>
          <div class="answer">
            <p>Jumlah SKS</p>
              {{mataKuliah.jumlahSks}} SKS
          </div>
        </div>
      </div>
      <div class="answer">
        <p>Deskripsi Kelas</p>
        {{mataKuliah.deskripsi}}
      </div>
    </div>
  </div>
   

{% endblock main %}

story5mk2/templates/siakenji_view.html
{% extends 'base5.html' %}
{% load static %}


{% block main %}
    <div class="row-center">
        <h1>Selamat Datang di Siak En Ji</h1>
    </div>
    <div class="column-center">
        {% for mataKuliah in listMataKuliah %}
        <div class="list-matkul">
            <div class="row-center">
                <a href={{mataKuliah.get_absolute_url}}>
                    {{mataKuliah.nama}}
                </a>
            </div>
            <div class="row-center">
                <div class="column-center-2">
                    <p>Ruangan: {{mataKuliah.ruangan}}</p>
                    <p>Dibawa oleh {{mataKuliah.dosen}}</p>
                </div>
                <div class="column-center-2" style="text-align: end; padding-right: 20px;">
                    <p>{{mataKuliah.semester}}</p>
                </div>
            </div>
            <form action="{% url 'story5mk2:deleteMatkul' mataKuliah.id %}" method="POST">
                {% csrf_token %}
                <button type="input">
                    Delete Mata Kuliah
                </button>
            </form>
        </div>
    {% endfor %}
    </div>
    

{% endblock main %}